debug = false
log_dir = "e:\\GIT_pros\\wadManager\\logs"
data_dir = "e:\\GIT_pros\\wadManager\\data"
temp_dir = "e:\\GIT_pros\\wadManager\\temp"
download_dir = "e:\\GIT_pros\\wadManager\\download"
output_dir = "E:\\GeziSkin\\Wads"
mod_dir = "e:\\GIT_pros\\wadManager\\mods"
load_mod_dir = "e:\\GIT_pros\\wadManager\\load_mods"
installed_mod_info_file = "installed.json"
